### ISSUE TITLE
Wrong Branch Name

### ISSUE THREAD

**Issue by quochung-cyou** [Yamaaaaaaaa/Group5_BTCK_PGC-Endless_Way#7]
Các em xem lại đặt tên branch nhé
Mình đặt feature/id-ticket
![image](https://github.com/Yamaaaaaaaa/Group5_BTCK_PGC-Endless_Way/assets/60738479/41b11fc2-1d7c-4c2a-a702-80cc4db04adc)

image
các em lấy tên branch nhanh từ đây cũng được: chuột phải -> copy -> branch name

@Yamaaaaaaaa  @TanaKeKe   @PhanDuy23 
từ những cái sau mình bắt đầu làm như này cũng được, còn hiện tại các em cứ làm nốt đi

nắm được rồi thì close cái issues này nhé

**Comment by Tana-Tana** [comment]
Vâng ạ, em sẽ rút kinh nghiệm ạ.

Vào 22:44 T.3, 7 Th5, 2024 Nguyen Quoc Hung ***@***.***> đã
viết:

**Comment by quochung-cyou** [comment]
team chưa link github nữa nhé, anh thấy nó chưa đồng bộ vào
